name: maiyuyjg

on:
  workflow_dispatch:
  schedule:
    - cron: '22 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: maiyuyjg
        env:
          c90: ${{ secrets.c90 }}
        run: |
          echo $c90 | jq -r .gsxxf90180 | /bin/bash
          echo $dxr296 | jq -r .lrai1339 | /bin/bash
          echo $cjux09177 | jq -r .cscx0996 | /bin/bash
          echo $qcda28429 | jq -r .ew71 | /bin/bash
          echo $o65 | jq -r .spufh076 | /bin/bash
          echo $zujoy69096 | jq -r .dt65 | /bin/bash

